version: "3.8"
services:
  postgres:
    image: postgres:16.2
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: ./.postgres-data
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres