package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"fmt"

	"github.com/Thiti-Dev/scrumerization-core-service/graph/model"
	context_type "github.com/Thiti-Dev/scrumerization-core-service/internal/domain/context"
	"github.com/Thiti-Dev/scrumerization-core-service/pkg/tokenizer"
	"github.com/google/uuid"
)

// CreateTopic is the resolver for the createTopic field.
func (r *mutationResolver) CreateTopic(ctx context.Context, input *model.CreateTopicInput) (*model.Topic, error) {
	userPayload := ctx.Value(context_type.UserDataCtxKey).(*tokenizer.Payload)
	room, err := r.RoomRepository.FindRoomByID(input.RoomID)
	if err != nil {
		return nil, err
	}

	if room == nil {
		return nil, fmt.Errorf("room with id:\"%v\" doesn't exist", input.RoomID)
	}

	if room.CreatorID != userPayload.UUID {
		return nil, fmt.Errorf("requires room owner to create topic")
	}

	topic, err := r.TopicRepository.CreateTopic(input)
	if err != nil {
		return nil, err
	}

	// Broadcasting to room [async]
	// Set the current Topic
	go func() {
		room := r.RoomHub.MustGetRoomFromRoomID(input.RoomID)
		room.SetCurrentTopic(topic.ID, topic.Name)
	}()

	return &model.Topic{
		ID:        topic.ID,
		RoomID:    topic.RoomID,
		Name:      topic.Name,
		AvgScore:  topic.AvgScore,
		IsActive:  topic.IsActive,
		CreatedAt: topic.CreatedAt,
		UpdatedAt: topic.UpdatedAt,
	}, nil
}

// CreateTopicVote is the resolver for the createTopicVote field.
func (r *mutationResolver) CreateTopicVote(ctx context.Context, input *model.CreateTopicVoteInput) (*model.TopicVote, error) {
	userPayload := ctx.Value(context_type.UserDataCtxKey).(*tokenizer.Payload)
	topicVote, err := r.TopicRepository.CreateTopicVote(userPayload.UUID, input)
	if err != nil {
		return nil, err
	}

	return &model.TopicVote{
		TopicID:   topicVote.TopicID,
		UserID:    topicVote.UserID,
		Voted:     int(topicVote.Voted),
		VotedDesc: topicVote.VotedDescription,
		CreatedAt: topicVote.CreatedAt,
		UpdatedAt: topicVote.UpdatedAt,
	}, nil
}

// Topics is the resolver for the topics field.
func (r *queryResolver) Topics(ctx context.Context, roomID uuid.UUID, password *string) ([]*model.Topic, error) {
	room, err := r.RoomRepository.FindRoomByID(roomID)
	if err != nil {
		return nil, err
	}
	if room == nil {
		return nil, fmt.Errorf("the room with id:\"%v\" doesn't exist", roomID)
	}
	if room.Password != nil {
		// If password is required
		if room.Password != password {
			return nil, fmt.Errorf("invalid room password given")
		}
	}

	topics, err := r.TopicRepository.GetTopicsFromSpecificRoom(roomID)
	if err != nil {
		return nil, err
	}
	var res []*model.Topic
	for _, topic := range topics {
		res = append(res, &model.Topic{
			ID:        topic.ID,
			RoomID:    topic.RoomID,
			Name:      topic.Name,
			AvgScore:  topic.AvgScore,
			IsActive:  topic.IsActive,
			CreatedAt: topic.CreatedAt,
			UpdatedAt: topic.UpdatedAt,
		})
	}

	return res, nil
}
