package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"

	"github.com/Thiti-Dev/scrumerization-core-service/graph/model"
)

// PrivateVersion is the resolver for the privateVersion field.
func (r *queryResolver) PrivateVersion(ctx context.Context) (*model.PrivateVersionResponse, error) {
	return &model.PrivateVersionResponse{
		Version: "1.0",
	}, nil
}
