// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/google/uuid"
)

type CreateUserInput struct {
	Username string `json:"username" jsonschema:"minLength=6,maxLength=32,required"`
	Password string `json:"password" jsonschema:"minLength=8,maxLength=64,required"`
	Name     string `json:"name" jsonschema:"minLength=3,required"`
}

type Mutation struct {
}

type Query struct {
}

type User struct {
	ID        uuid.UUID `json:"id"`
	Username  *string   `json:"username,omitempty"`
	Name      *string   `json:"name,omitempty"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}
