//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type TopicVotes struct {
	TopicID          uuid.UUID
	UserID           uuid.UUID
	Voted            int32
	VotedDescription *string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}
