//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Topics struct {
	ID        uuid.UUID `sql:"primary_key"`
	RoomID    uuid.UUID
	Name      string
	AvgScore  *float64
	CreatedAt time.Time
	UpdatedAt time.Time
}
